name: flutter_ci

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'android/**'
      - 'assets/**'
      - 'web/**'
      - 'test/**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1
          cache: true
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter test
      - run: dart format lib/
      - run: dart fix --apply
      - run: dart analyze --fatal-infos
      - run: dart run import_sorter:main

      - name: Commit format fixes
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "style: auto format and fix" || echo "No changes to commit"
          git push

      - name: Build APK
        if: startsWith(github.ref, 'refs/tags/')
        run: flutter build apk --release
      
      - name: Upload APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.AWATTACKER_TOKEN }}